class AlreadyExistError(Exception):
    """Raised when trying to save an Todo that already exist"""
